language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
- pip install -r requirements
- python setup.py install
- echo "import homer;conf = homer.Config(app='test')" | python
script:
- gunzip ./test/performance.gz
- python ./test/loadtest.py
- python ./test/dumptest.py
